title: Rachel Blog
remote_theme: just-the-docs/just-the-docs

color_scheme: light
search_enabled: true

url: https://chewon1227.github.io

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache