title: Rachel Docs 
description: chasing questions - psychology and ai 

color_scheme: light
search_enabled: true 

url: https://chewon1227.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap   
  - jekyll-include-cache 

nav:
  - Home: index.md
  - Posts:
      - NLP: _pages/posts/nlp.md
      - Paper: _pages/posts/paper.md

heading_anchors: true